name: drazzle
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_lint: ^3.0.3
  # Routing
  go_router: ^17.1.0


  # UI
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  flutter_svg: ^2.2.3


  # Firebase
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5

  flutter_local_notifications: ^19.5.0


  # image from gallery
  permission_handler: ^12.0.1
  image_picker: ^1.2.1
  image: ^4.7.2
  share_plus: ^12.0.1

  # Path provider for file system access
  path_provider: ^2.1.5

  # Validation
  email_validator: ^3.0.0
  # logger
  talker_flutter: ^5.1.13


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.14.4"
  mockito: ^5.6.3
  build_runner: ^2.10.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/logo.png"
  min_sdk_android: 21 
  windows:
    generate: true
    image_path: "assets/png/logo.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/png/logo.png"

  # Linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf