name: drazzle
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: 3.0.3


  # Routing
  go_router: 17.1.0


  # UI
  cupertino_icons: 1.0.8
  shimmer: 3.0.0
  flutter_svg: 2.2.3


  # Firebase
  firebase_auth: 6.1.4
  firebase_core: 4.4.0
  cloud_firestore: 6.1.2
  firebase_storage: 13.0.6

  flutter_local_notifications: 19.5.0


  # image from gallery
  permission_handler: ^12.0.1
  image_picker: 1.2.1
  image: 4.7.2
  share_plus:   12.0.1

  image_gallery_saver_plus: ^4.0.1

  # Path provider for file system access
  path_provider: 2.1.5

  # Validation
  email_validator: 3.0.0
  
  # Network connectivity
  connectivity_plus: 7.0.0

  # logger
  talker_flutter: 5.1.13


dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: 5.6.3
  build_runner: 2.10.5

  # Linting
  flutter_lints: 6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf